# service call to control a robot through an affordance template

# command types
uint8 PLAN = 0
uint8 EXECUTE = 1

# uint8 PLAY_BACKWARD = 2
# uint8 PLAY_FORWARD = 3
# uint8 STEP_BACKWARD = 4
# uint8 STEP_FORWARD = 5
# uint8 CURRENT = 6
# uint8 PAUSE = 7
# uint8 STOP = 8

# the template type
string type

# the template id
uint8 id

# which command type (as above)
uint8 command

# which end effectors to plan/execute
string[] end_effectors

# the goal IDs for each end-effector
uint8 waypoint_goal_ids[]

# go directly to the waypoint (if not adjacent)
bool direct

# execute on plan or just plan
# bool execute_on_plan

# check to see if there is a precomputed path and use that
# bool execute_precomputed_plan

---

# return status
bool status

# which command type (as above)
uint8 command

# info to know what the state of everything is
AffordanceTemplateStatus affordance_template_status 
