# service call to plan trajectories for an affordance template

# the template type
string type

# the template id
uint8 id

# the template trajectory
string trajectory_name

# which end effectors to plan
string[] end_effectors

# the goal IDs for each end-effector
uint8[] waypoint_goal_ids

# go directly to the waypoint (if not adjacent)
bool direct

---

# return status
bool status

# info to know what the state of everything is
AffordanceTemplateStatus affordance_template_status 
