#goal
string[] groups
string trajectory
int32 steps # 0 to plan for all steps in trajectory
bool direct
bool backwards # UNDEFINED ACTION - not really implemented as of 12/9/2015 @seth
bool execute_on_plan
---
#result
bool succeeded
---
#feedback
int32 progress # should be increasing if progress being made, -1 otherwise 